#!/usr/bin/env sh
#=========================================================================
# Author: Gaetan (gaetan@ictpourtous.com) - Twitter: @astsu777
# Creation: Sun 22 Aug 2021 12:24:13
# Last modified: Sun 22 Aug 2021 12:24:19
# Version: 1.0
#
# Description: print the current RAM usage
#=========================================================================

usage=$(free -t | awk 'NR == 2 {print $3/$2*100}' | cut -d'.' -f1)
icon="🧠"
printf "%s %s\\n" "$icon" "$usage%"
