#!/usr/bin/env sh
#=========================================================================
# Author: Gaetan (gaetan@ictpourtous.com) - Twitter: @GaetanICT
# Creation: Sun 22 Aug 2021 12:24:38
# Last modified: Sun 22 Aug 2021 12:24:48
# Version: 1.0
#
# Description: print unread news from Newsboat
#=========================================================================

news=$(newsboat -x print-unread | awk '{print $1}')
icon="📰"
printf "%s %s\\n"  "$icon" "$news"
