#!/usr/bin/env sh
#=========================================================================
# Author: Gaetan (gaetan@ictpourtous.com) - Twitter: @astsu777
# Creation: Sun 22 Aug 2021 12:26:03
# Last modified: Sun 22 Aug 2021 12:26:09
# Version: 1.0
#
# Description: print the current date and time
#=========================================================================

dte="$(date +"%a %B %d %R"| sed 's/  / /g')"
icon="🕒"
printf "%s %s\n" "$dte"
