#!/usr/bin/env sh
#=========================================================================
# Author: Gaetan (gaetan@ictpourtous.com) - Twitter: @astsu777
# Creation: Sun 22 Aug 2021 12:26:28
# Last modified: Mon 23 Aug 2021 00:04:31
# Version: 1.0
#
# Description: get the disk space of '/' mount point
#=========================================================================

hdd1="$(df -h / | awk 'NR==2 {print $3}')"
hdd2="$(df -h / | awk 'NR==2 {print $2}')"
icon="💾"
printf "%s %s\\n" "D:" "$hdd1"/"$hdd2 "
