#!/usr/bin/env sh
#=========================================================================
# Author: Gaetan (gaetan@ictpourtous.com) - Twitter: @astsu777
# Creation: Sun 22 Aug 2021 12:26:38
# Last modified: Mon 23 Aug 2021 00:04:37
# Version: 1.0
#
# Description: print the current RAM usage
#=========================================================================

usage=$(free -t | awk 'NR == 2 {print $3/$2*100}' | cut -d'.' -f1)
icon="🧠"
printf "%s %s\\n" "M:" "$usage%"
