#!/usr/bin/env sh
#=========================================================================
# Author: Gaetan (gaetan@ictpourtous.com) - Twitter: @GaetanICT
# Creation: Sun 22 Aug 2021 12:26:57
# Last modified: Mon 23 Aug 2021 00:04:55
# Version: 1.0
#
# Description: print unread news from Newsboat
#=========================================================================

news=$(newsboat -x print-unread | awk '{print $1}')
icon="📰"
printf "%s %s\\n"  "N:" "$news"
